### PR TITLE
upgrade to angular 13

### PR DESCRIPTION
**Pull request by anikets43**
refer: update.angular.io for the upgrade. for peer deps, we
need to update that manually

### CODE REVIEW

**Comment by TomasKostadinov** [comment]
```bash

------------------------------------------------------------------------------
Building entry point 'angular-feather/icons'
------------------------------------------------------------------------------
✔ Compiling with Angular sources in Ivy full compilation mode.
✔ Bundling to FESM2015
✔ Bundling to UMD
✔ Writing package metadata
✔ Built angular-feather/icons

------------------------------------------------------------------------------
Built Angular Package
 - from: /Users/tomas/code/angular-feather/projects/angular-feather
 - to:   /Users/tomas/code/angular-feather/dist/angular-feather
------------------------------------------------------------------------------

Build at: 2021-12-28T15:32:01.564Z - Time: 4912ms

```

Looks good to me! @anikets43 Thank you very much for this quick fix!

@michaelbazos Maybe you could merge this and release a new version to npm?

**Comment by anikets43** [comment]
@michaelbazos Could you please merge and do `npm publish`

**Review by icruz-dev — APPROVED** [review]

**Comment by icruz-dev** [comment]
Sorry, I didn't mean to do that. Kindly disregard/remove my review.

**Comment by michaelbazos** [comment]
Hi @anikets43 
Apologies for the absence, and thank you for the contribution!
I am taking care of the next steps, regarding the publishing of the update to the npm library.

**Pull request merged**
