### PR TITLE
Export Components

### LINKED ISSUE #2: Can't use programmatically
Let say we have menu which consist of items with icon and text. By angular concepts we should define array of objects that represents each menu item. Then we go through this items in *ngFor loop and print  items one by one. 
```
<button menuClose ion-item detail-none *ngFor="let p of pages" (click)="openPage(p)">
        <ion-icon [name]="p.icon"></ion-icon>
        {{p.title}}
</button>
```
How we should implement this behaviour with angular-feather? ngSwitch?

### PR DESCRIPTION
**Pull request by mweathers**
This specifies each component as an `entryComponent` and exports the Components alongside their respective modules.

This fixes #2 by allowing a structural directive to create the component programmatically as in the example below.

```
import { Directive, ViewContainerRef, Input, ComponentFactoryResolver, Renderer2, OnInit } from '@angular/core';

@Directive({
  selector: '[featherIcon]',
})
export class FeatherIconDirective implements OnInit {
  @Input('featherIcon') component: any;
  @Input('featherIconClass') class: any;

  constructor(private componentFactoryResolver: ComponentFactoryResolver, private viewContainerRef: ViewContainerRef, private renderer2: Renderer2) {}

  ngOnInit() {
    this.viewContainerRef.clear();
    const componentFactory = this.componentFactoryResolver.resolveComponentFactory(this.component);
    const componentRef = this.viewContainerRef.createComponent(componentFactory);
    this.renderer2.addClass(componentRef.location.nativeElement, this.class);
  }
}
```

Example Usage:
```
items = [
    { iconComponent: IconBookOpenComponent },
    { iconComponent: IconMessageSquareComponent }
];

<div *ngFor="let item of items">
    <div *featherIcon="item.iconComponent;class:'help-menu-item__icon'"></div>
    <div>{{ item.label }}</div>
</div> 

```

### CODE REVIEW

**Comment by michaelbazos** [comment]
Thanks for the pull request @mweathers !

Given the documentation at https://angular.io/guide/entry-components, my understanding is that since each icon become an entryComponent, that would prevent it from being tree-shaken, even if unused?

**Comment by mweathers** [comment]
Ah, yes, I hadn't thought  about that. Would it be better if I modified the PR to only export the components, and let the client import them and declare them as entry components as needed?

**Comment by michaelbazos** [comment]
I've been thinking the same, i.e. to let the client declare the entry components, but on the other hand the solution seems to sacrifice intuitiveness and ease of use.
Another thing that bothered me is that, I believe in the case of #2, the problem is to instantiate an icon given only the name as a string. So I thought coming with the following usage:

    <i-feather name="heart"></i-feather>

What do you think of the above usage? This would solve #2. 
Of course the requirement of bundling only a subset of icons still applies. I've been working towards this direction, and the result is for now visible on the [develop branch](https://github.com/michaelbazos/angular-feather/tree/develop)

**Comment by mweathers** [comment]
Yes, I believe that approach is a better solution. Thanks for moving quick on this!

**Comment by michaelbazos** [comment]
Thank you as well! Although eventually not merged, your contribution was of great help and triggered a key update.

**Pull request closed without merging**
