### PR TITLE
fix(): Relax angular peer dependency

### LINKED ISSUE #59: Update to angular ~13.2.0
Hey guy, can you update angular version to ~13.2.0?

Tkssss,

### LINKED ISSUE #62: Angular 14 support
Hello,

Can add support of Angular 14.

For information, stacktrace :

```npm ERR! While resolving: angular-feather@6.3.0
npm ERR! Found: @angular/common@14.0.0
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"^14.0.0 || ^15.0.0" from @angular/cdk@14.0.0
npm ERR!   node_modules/@angular/cdk
npm ERR!     peer @angular/cdk@"14.0.0" from @angular/material@14.0.0
npm ERR!     node_modules/@angular/material
npm ERR!       @angular/material@"^14.0.0" from the root project
npm ERR!     @angular/cdk@"^14.0.0" from the root project
npm ERR!   peer @angular/common@"14.0.0" from @angular/forms@14.0.0
npm ERR!   node_modules/@angular/forms
npm ERR!     peer @angular/forms@"^14.0.0 || ^15.0.0" from @angular/material@14.0.0
npm ERR!     node_modules/@angular/material
npm ERR!       @angular/material@"^14.0.0" from the root project
npm ERR!     peer @angular/forms@">=9.0.0" from @ckeditor/ckeditor5-angular@4.0.0
npm ERR!     node_modules/@ckeditor/ckeditor5-angular
npm ERR!       @ckeditor/ckeditor5-angular@"^4.0.0" from the root project
npm ERR!     2 more (the root project, @ng-bootstrap/ng-bootstrap)
npm ERR!   14 more (@angular/material, @angular/platform-browser, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"~13.1.1" from angular-feather@6.3.0
npm ERR! node_modules/angular-feather
npm ERR!   angular-feather@"^6.3.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/common@13.1.3
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"~13.1.1" from angular-feather@6.3.0
npm ERR!   node_modules/angular-feather
npm ERR!     angular-feather@"^6.3.0" from the root project
npm ERR!
```

### PR DESCRIPTION
**Pull request by moberwasserlechner**
closes #62 
closes #59

### CODE REVIEW

**Comment by michaelbazos** [comment]
Thanks Michael.

Is the changelog generated by a tool?

**Comment by michaelbazos** [comment]
Note, I released earlier today 6.4.1, which aligns the angular peer dependencies version in the library's package.json with the package.json file at root, that is to version ^14, but I am up for relaxing the version, as well as integrating other changes from this PR.

**Comment by moberwasserlechner** [comment]
Hi Michael,

re changelog) No I added it manually but we could use sth like "standard-version" but at the time I was faster by adding it manually

re 6.4.1)  I increase the PR version to 6.5.0 as that would better identify the upgrade of the lib.

Moreover I further relaxed the peer dependency to >=11. The lib uses Angular's most basic features, therefore I think it would be save to let user with older Angular versions use the lib's new release. What do you think about that?

I think I can test with Angular 11, 12 and 14 tomorrow using a local build tomorrow.

**Comment by michaelbazos** [comment]
> Moreover I further relaxed the peer dependency to >=11. The lib uses Angular's most basic features, therefore I think it would be save to let user with older Angular versions use the lib's new release. What do you think about that?

I agree with the approach, this is better for retro-compatibility.

**Comment by moberwasserlechner** [comment]
Unfortunately my idea to just change the peer dependency does not work as intended. Testing with Angular 12 results in this error.

```
./node_modules/angular-feather/fesm2015/angular-feather.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: Cannot create property 'message' on string '\node_modules\angular-feather\fesm2015\angular-feather.mjs: This application depends upon a library published using Angular version 14.0.5, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.
  33 | }
  34 | FeatherComponent.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "14.0.5", ngImport: i0, type: FeatherComponent, deps: [{ token: ElementRef }, { token: ChangeDetectorRef }, { token: Icons }], target: i0.ɵɵFactoryTarget.Component });
> 35 | FeatherComponent.ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "14.0.0", version: "14.0.5", type: FeatherComponent, selector: "i-feather, feather-icon", inputs: { name: "name" }, usesOnChanges: true, ngImport: i0, template: "<ng-content></ng-content>\r\n", styles: [":host{display:inline-block;width:24px;height:24px;fill:none;stroke:currentColor;stroke-width:2px;stroke-linecap:round;stroke-linejoin:round}\n"] });
     |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  36 | i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "14.0.5", ngImport: i0, type: FeatherComponent, decorators: [{
  37 |             type: Component,
  38 |             args: [{ selector: 'i-feather, feather-icon', template: "<ng-content></ng-content>\r\n", styles: [":host{display:inline-block;width:24px;height:24px;fill:none;stroke:currentColor;stroke-width:2px;stroke-linecap:round;stroke-linejoin:round}\n"] }]'
    at run (node_modules\@babel\core\lib\transformation\index.js:37:15)
    at run.next (<anonymous>)
    at Function.transform (node_modules\@babel\core\lib\transform.js:25:41)
    at transform.next (<anonymous>)
    at step (node_modules\gensync\index.js:261:32)
    at node_modules\gensync\index.js:273:13
    at async.call.result.err.err (node_modules\gensync\index.js:223:11)
    at node_modules\gensync\index.js:189:28
    at node_modules\@babel\core\lib\gensync-utils\async.js:73:7
    at node_modules\gensync\index.js:113:33
```

**Comment by michaelbazos** [comment]
With angular 13 you get no error?

**Comment by moberwasserlechner** [comment]
I've not tested with Angular 13 yet but I'll give it another try on the weekend.

**Comment by moberwasserlechner** [comment]
I downgraded the Angular version the lib is developed with because applications using a library need to use a Angular version greater or equal that the Angular version the lib is developed in.

See https://angular.io/guide/creating-libraries#ensuring-library-version-compatibility for details.

**Comment by moberwasserlechner** [comment]
I tested with Angular 12, 13 and 14 applications and so far I works fine :)

**Comment by moberwasserlechner** [comment]
This would PR is ready to be merged. I found no further problems. Plz review.

**Review by michaelbazos — APPROVED** [review]
👍

**Comment by moberwasserlechner** [comment]
Do you know when you probably will release/publish to npm?

**Comment by michaelbazos** [comment]
My bad for the delay. Version 6.5.0 is now public on npm registry.

**Pull request merged**
